server:
      port: 8099  #配置端口
      address : localhost
      session-timeout: 30
      tomcat.max-threads: 0
      tomcat.uri-encoding: UTF-8


spring:
      datasource:
                  names: order0-master,order0-slave,order1-master,order1-slave,order2-master,order2-slave,order3-master,order3-slave,business0-master,business0-slave,business1-master,business1-slave
                  order0-master:
                                  url: jdbc:mysql://172.16.2.134:33066/order0?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order0-slave:
                                  url: jdbc:mysql://172.16.2.134:33066/order0?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order1-master:
                                  url: jdbc:mysql://172.16.2.134:33066/order1?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order1-slave:
                                  url: jdbc:mysql://172.16.2.134:33066/order1?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order2-master:
                                  url: jdbc:mysql://172.16.2.134:33066/order2?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order2-slave:
                                  url: jdbc:mysql://172.16.2.134:33066/order2?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order3-master:
                                  url: jdbc:mysql://172.16.2.134:33066/order3?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  order3-slave:
                                  url: jdbc:mysql://172.16.2.134:33066/order3?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  business0-master:
                                  url: jdbc:mysql://172.16.2.134:33066/business0?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  business0-slave:
                                  url: jdbc:mysql://172.16.2.134:33066/business0?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  business1-master:
                                  url: jdbc:mysql://172.16.2.134:33066/business1?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  business1-slave:
                                  url: jdbc:mysql://172.16.2.134:33066/business1?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver
                  sharding-expand:
                                  url: jdbc:mysql://172.16.2.134:33066/business1?characterEncoding=UTF-8
                                  username: root
                                  password: root
                                  driverClassName: com.mysql.jdbc.Driver

      devtools:
              restart:
                      enabled: true #热部署生效
                      additional-paths: sharding-expand/src/main/java  #设置重启的目录
#                      exclude: WEB-INF/**   #classpath目录下的WEB-INF文件夹内容修改不重启
sharding:
          database:
                    available: 4
          table:
                    available: 4
          datasource:
                      default:
                                url: jdbc:mysql://172.16.2.134:33066/shardingrule?characterEncoding=UTF-8
                                username: root
                                password: root
                                driverClassName: com.mysql.jdbc.Driver

mybatis:
        configLocations: mybatis/mybatis-config.xml
        mapperLocations: classpath*:mybatis/mapper/*.xml
        typeAliasesPackage: com.abin.lee.sharding.expand.api.model


# LOGGING  INFO  DEBUG
logging:
        level:
              root: INFO
              org:
                  springframework: INFO
                  hibernate: INFO
#        path: F:\\
#        file: log.log
              com:
                  ibatis: INFO
                  abin:
                        lee:
                            sharding:
                                      dbtable:
                                              api:
                                                  mapper: INFO



# true false
debug: false













